In [1]:
import numpy as np

In [2]:
df1=np.array([1,2,3,4,5])
print(df1)

[1 2 3 4 5]


In [3]:
type(df1)

numpy.ndarray

In [4]:
df1.ndim

1

In [5]:
df2=np.array([[1,2,3,4,5],[13,14,15,16,17]])
print(df2)

[[ 1  2  3  4  5]
 [13 14 15 16 17]]


In [6]:
type(df2)

numpy.ndarray

In [7]:
df2.ndim


2

In [8]:
df1.size

5

In [9]:
df2.size

10

In [10]:
df1.shape

(5,)

In [11]:
type(df2)

numpy.ndarray

In [12]:
df2.shape

(2, 5)

In [13]:
df2.dtype

dtype('int32')

In [14]:
df2

array([[ 1,  2,  3,  4,  5],
       [13, 14, 15, 16, 17]])

In [15]:
df3=np.array([[1,1,1],[1,1,1],[1,1,1]])
df3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
df3.shape

(3, 3)

In [17]:
df3.dtype

dtype('int32')

In [18]:
#numpy array for same list
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [19]:
df3=np.ones(7)

In [20]:
df3

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
df3.dtype

dtype('float64')

In [22]:
df4=np.ones((3,4))
df4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
df4.shape

(3, 4)

In [24]:
#if we dont want floting num .. so make it intiger .
df5=np.ones((3,4),dtype=int)

In [25]:
df5

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
df6=np.zeros((4,6))
df6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
df6=np.zeros((4,6),dtype=bool)
df6

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [28]:
df6=np.zeros((4,6),dtype=str)
df6

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [29]:
#EMPTY MATRIX
em_mt=np.empty((3,6))
em_mt

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56591659e-307, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.60220393e-306, 1.78018811e-306,
        6.89807188e-307, 7.56596412e-307, 8.34451503e-308]])

# NUMPY FUNCTION

In [30]:
#np.arange(strt,ende,steps)

df7=np.arange(1,13)

In [31]:
df7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
df7=np.arange(1,13,3)
df7

array([ 1,  4,  7, 10])

# LINSPACE()

In [33]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# RESHAPE

In [38]:
df8=df7.reshape(3,4)
df8

ValueError: cannot reshape array of size 4 into shape (3,4)

In [35]:
df7

array([ 1,  4,  7, 10])

In [39]:
df8=np.arange(1,16).reshape(5,3)
df8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [40]:
df8.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
df8.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
df8.transpose()

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [44]:
#ONLT .T CAN ALSO EXPOSE TRANSPOSE
df8.T

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

# MATHEMATIC OPERATION USING NUMPY

In [45]:
import numpy as np

In [48]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [51]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [52]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [57]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [58]:
#matrix
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [59]:
#same matrix 
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [60]:
# find out maximum funtion from matrix 
arr1.max()

9

In [61]:
#maximum value index 
arr1.argmax()

8

In [62]:
arr1.max(axis=1)

array([3, 6, 9])

In [64]:
#axis = 1 represent row . and = 0 represent column
arr2.max(axis=1)

array([3, 6, 9])

In [65]:
arr1.min()

1

In [66]:
arr1.argmin()

0

In [67]:
arr1.max(axis=0)

array([7, 8, 9])

In [68]:
arr1.min(axis=0)

array([1, 2, 3])

In [69]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr1.sum()

45

In [72]:
#TO FIND EVERY row SUM 
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [73]:
# to find all column total 
np.sum(arr1,axis=0)

array([12, 15, 18])

In [74]:
# mean (average )
np.mean(arr1)

5.0

In [75]:
#to find squire root 
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [76]:
#to find standard division 
np.std(arr1)

2.581988897471611

In [77]:
#to find exponent ( to the power x )
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [78]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [79]:
#to find log base 10 )
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# python numpy array slicing(:)

In [153]:
arr3=np.arange(0,100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [155]:
#to arrange how many row and how many column)
arr3.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [156]:
arr3[1]

1

In [157]:
max(arr3)

99

In [146]:
len(arr3.shape)

1

In [123]:
arr3.mean()

50.5

In [147]:
arr3[0:1]

array([0])

In [162]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [163]:
arr3.ndim

1

In [164]:
arr3[0].ndim

0

In [169]:
arr3[0]

0

In [170]:
arr3[:,0:1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [173]:
arr3[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [178]:
arr3[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [184]:
arr3[0]

0

# PYTHON NUMPY ARRAY CONCTINATION AND SPLLT

In [185]:
import numpy as np
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [190]:
arr4=np.arange(1,17).reshape(4,4)
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [191]:
arr5=np.arange(17,33).reshape(4,4)
print(arr5)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [192]:
#conctination list 
list1=[2,4,6,8,10]
list=[12,14,16,18]
print(list1+list)


[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [193]:
arr4+arr5

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [196]:
#concatenate(())
np.concatenate((arr4,arr5))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [198]:
np.concatenate((list1,list))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [201]:
#concatenate row column wise 
np.concatenate((arr4,arr5),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [202]:
np.vstack((arr4,arr5))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [207]:
#horizantal 
np.hstack((arr4,arr5))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [208]:
#break ..or split 
np.split(arr4,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [210]:
np.split(arr5,2)

[array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [213]:
np.split(arr5,2,axis=1)

[array([[17, 18],
        [21, 22],
        [25, 26],
        [29, 30]]),
 array([[19, 20],
        [23, 24],
        [27, 28],
        [31, 32]])]